import Head from "next/head";
import Setup from "~/components/setup";
import { useAppState } from "~/stores/form";
import { useUserStore } from "~/stores/user";

export default function Home() {
  const { apikey } = useUserStore();
  const { page, setPage } = useAppState();

  // determine if we have an apikey already

  return (
    <>
      <Head>
        <title>Woo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {page === "loading" && <h1>Loading...</h1>}
        {page === "setup" && <Setup />}
      </main>
    </>
  );
}
